### ISSUE TITLE
请问这个可以改成页面弹出需要确认的自动确认么

### ISSUE THREAD

**Issue by banduoba** [hxchen/ChromeAddin-mafengwo#1]
setInterval(() => {
        const buttonEle = document.getElementsByClassName('next-btn next-medium next-btn-primary next-dialog-btn')[0];
        if (buttonEle) buttonEle.click();
}, 2000)

这个是我在浏览器控制台运行的代码可以自动点击确认,不过每次都需要运行,请问插件里面怎么弄下呢 谢谢啊

**Comment by hxchen** [comment]
> 

那你需要来监控确认对话框状态，然后脚本模拟点击确认。
